const { italic } = require("colorette")

describe('Address Book', () => {
  beforeEach(() => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > :nth-child(2) > a').click()
    cy.url().should('contain','/customer/account/login/')  
    cy.get('#email').type('tes.mbagasrw@yopmail.com')
    cy.get('#pass').type('Welcome@123')
    cy.get('#send2').click()
  })

  it('Passed to Edit Address Book', () => {
    cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('Bagas')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('Bagas')
    cy.get('#company').clear()
    cy.get('#company').type('Student')
    cy.get('#telephone').clear()
    cy.get('#telephone').type('08512345678')
    cy.get('#street_1').clear()
    cy.get('#street_1').type('Jl.Sanber')
    cy.get('#street_2').clear()
    cy.get('#street_2').type('no.53')
    cy.get('#street_3').clear()
    cy.get('#street_3').type('Grogol')
    cy.get('#country', {timeout: 10000}).select('Indonesia')
    cy.get('#region').clear()
    cy.get('#region').type('DKI Jakarta')
    cy.get('#city').clear()
    cy.get('#city').type('Jakarta Barat')
    cy.get('#zip').clear()
    cy.get('#zip').type('12345').wait(2000)
    cy.get('.action.save.primary').click()
    cy.wait(2000)
  })

  it('Failed to Edit Address Book - Mandatory Field Empty', () => {
    cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    cy.get('#firstname').clear()
    cy.get('#lastname').clear()
    cy.get('#telephone').clear()
    cy.get('#street_1').clear()
    cy.get('#street_2').clear()
    cy.get('#street_3').clear()
    cy.get('#country', {timeout: 10000}).select('Indonesia')
    cy.get('#city').clear()
    cy.get('#zip').clear().wait(2000)
    cy.get('.action.save.primary').click()
    cy.wait(2000)
  })

  it('Failed to Edit Address Book - Non Mandatory Field Empty', () => {
    cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    cy.get('#company').clear()
    cy.get('#region').clear().wait(2000)
    cy.get('.action.save.primary').click()
    cy.wait(2000)
  })
})