const { italic } = require("colorette")
import objAddressbook from "../../../support/page-obj-addressbook/obj-addressbook"

describe('Address Book', () => {
  beforeEach(() => {
    cy.visit('https://magento.softwaretestingboard.com/')
    cy.get('.panel > .header > :nth-child(2) > a').click()
    cy.url().should('contain','/customer/account/login/')  
    cy.get(objAddressbook.email).type('tes.mbagasrw@yopmail.com')
    cy.get(objAddressbook.pass).type('Welcome@123')
    cy.get(objAddressbook.buttonLogin).click()
  })

  it('Passed to Edit Address Book', () => {
    //cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    //cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    //cy.get('.body > div.page-wrapper > header > div.panel.wrapper > div > ul > li.customer-welcome.active > div > ul > li:nth-child(1) > a').click()
    //cy.select('a[href="https://magento.softwaretestingboard.com/customer/account/"]')
    //cy.get('.action.switch', {timeout: 10000}).click()
    cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    cy.get(objAddressbook.firstname).clear()
    cy.get(objAddressbook.firstname).type('Bagas')
    cy.get(objAddressbook.lastname).clear()
    cy.get(objAddressbook.lastname).type('Bagas')
    cy.get(objAddressbook.company).clear()
    cy.get(objAddressbook.company).type('Student')
    cy.get(objAddressbook.telephone).clear()
    cy.get(objAddressbook.telephone).type('08512345678')
    cy.get(objAddressbook.street_1).clear()
    cy.get(objAddressbook.street_1).type('Jl.Sanber')
    cy.get(objAddressbook.street_2).clear()
    cy.get(objAddressbook.street_2).type('no.53')
    cy.get(objAddressbook.street_3).clear()
    cy.get(objAddressbook.street_3).type('Grogol')
    cy.get(objAddressbook.country, {timeout: 10000}).select('Indonesia')
    cy.get(objAddressbook.region).clear()
    cy.get(objAddressbook.region).type('DKI Jakarta')
    cy.get(objAddressbook.city).clear()
    cy.get(objAddressbook.city).type('Jakarta Barat')
    cy.get(objAddressbook.zip).clear()
    cy.get(objAddressbook.zip).type('12345').wait(2000)
    cy.get(objAddressbook.buttonSaveAddressBook).click()
    cy.wait(2000)
  })

  it('Edit Address Book - Mandatory Field Empty', () => {
    cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    cy.get(objAddressbook.firstname).clear()
    cy.get(objAddressbook.lastname).clear()
    cy.get(objAddressbook.telephone).clear()
    cy.get(objAddressbook.street_1).clear()
    cy.get(objAddressbook.street_2).clear()
    cy.get(objAddressbook.street_3).clear()
    cy.get(objAddressbook.country, {timeout: 10000}).select('Indonesia')
    cy.get(objAddressbook.city).clear()
    cy.get(objAddressbook.zip).clear().wait(2000)
    cy.get(objAddressbook.buttonSaveAddressBook).click()
    cy.get('#firstname-error').should('be.visible').and('contain.text', 'This is a required field.')
    cy.get('#lastname-error').should('be.visible').and('contain.text', 'This is a required field.')
    cy.get('#telephone-error').should('be.visible').and('contain.text', 'This is a required field.')
    cy.get('#street_1-error').should('be.visible').and('contain.text', 'This is a required field.')
    cy.get('#city-error').should('be.visible').and('contain.text', 'This is a required field.')
    cy.get('#zip-error').should('be.visible').and('contain.text', 'This is a required field.')
    cy.wait(2000)
  })

  it('Edit Address Book - Non Mandatory Field Empty', () => {
    cy.visit('https://magento.softwaretestingboard.com/customer/address/edit/id/24922/')
    cy.get(objAddressbook.company).clear()
    cy.get(objAddressbook.region).clear().wait(2000)
    cy.get(objAddressbook.buttonSaveAddressBook).click()
    cy.wait(2000)
  })
})